Repository spyder-ide/spyder-docs, pull requests merged in 2018-05, with the labels that each got.

#21 PR: Consistent look and feel with the rest of the website
  doc/_static/custom.css
  doc/_static/favicon.ico
  doc/_templates/layout.html
  doc/conf.py
Labels: status:Ready for Review, type:Task

#27 PR: Fix remaining layout issues with sidebar heading font size and element margin heights
  doc/_static/custom.css
Labels: status:Ready for Review, type:Bug

#31 PR: Remove man page and man section from conf.py
  doc/conf.py
  doc/manpage.rst
Labels: status:Ready for Review, type:Task

#34 PR: Re-add readme banner and move to _static
  README.md
  doc/_static/spyder_readme_banner.png
Labels: type:Bug

#36 PR: Clarify authors to avoid ambiguity with main repo, include links to repo contributors, and add doc maintainer contact info
  AUTHORS
  AUTHORS.txt
  LICENSE.txt
  README.md
  doc/conf.py
Labels: status:Ready for Review, type:Task

#44 PR: Baseline pass to fix/update existing content, copyedit, and conform to style guide
  doc/debugging.rst
  doc/editor.rst
  doc/fileexplorer.rst
  doc/findinfiles.rst
  doc/help.rst
  doc/historylog.rst
  doc/images/debugging/breakpoints_standard.png
  doc/images/dialog/dialog_new_project.png
  doc/images/internal_console/internal_console_contextmenu_settings.png
  doc/images/menu/menu_debug.png
  doc/index.rst
  doc/installation.rst
  doc/internalconsole.rst
  doc/ipythonconsole.rst
  doc/onlinehelp.rst
  doc/options.rst
  doc/overview.rst
  doc/projects.rst
  doc/pylint.rst
  doc/variableexplorer.rst
Labels: status:Ready for Review, type:Enhancement

#49 PR: Add the Sphinx link checker to CI checks, and touch all files to ensure all are checked
  .travis.yml
Labels: status:Ready for Review, type:Task

#50 PR: Add more explicit file type rules to gitattributes and make sure linguist doesn't ignore docs
  .gitattributes
Labels: type:Task
