Repository spyder-ide/spyder-docs, pull requests merged in 2018-07, with the labels that each got.

#57 PR: Change footer to match main website
  doc/_static/custom.css
  doc/_templates/layout.html
  doc/conf.py
Labels: type:Task

#70 PR: Update procedure to connect to external kernels for Spyder 3.3
  doc/ipythonconsole.rst
Labels: status:Ready for Review, type:Spyder Change

#29 PR: Eliminate redundant links from sidebar, add standard links to readme and fix minor layout bugs
  README.md
  doc/_static/custom.css
  doc/_templates/layout.html
  doc/conf.py
Labels: status:Ready for Review, type:Task
