Repository spyder-ide/spyder-docs, pull requests merged in 2020-08, with the labels that each got.

#140 PR: Update and improve Find pane docs for Spyder 4
  doc/findinfiles.rst
  doc/images/find_in_files/find-in-files-case.gif
  doc/images/find_in_files/find-in-files-directory.gif
  doc/images/find_in_files/find-in-files-extensions.gif
  doc/images/find_in_files/find-in-files-inprogress.png
  doc/images/find_in_files/find-in-files-max-results.png
  doc/images/find_in_files/find-in-files-regex.gif
  doc/images/find_in_files/find-in-files-search.gif
  doc/images/find_in_files/find_in_files_inprogress.png
  doc/indexpanes.rst
Labels: type:Enhancement, type:Spyder Change

#143 PR: Add a custom bottom margin to sections with cards
  doc/_static/custom_styles.css
Labels: type:Task

#148 PR: Refactor FA icon coloring in CSS to be more robust
  doc/_static/custom_styles.css
  doc/index.rst
Labels: status:Ready for Review, type:Task

#147 PR: Center images by default
  doc/_static/custom_styles.css
  doc/debugging.rst
  doc/editor.rst
  doc/help.rst
  doc/installation.rst
  doc/ipythonconsole.rst
  doc/plots.rst
  doc/profiler.rst
  doc/projects.rst
  doc/pylint.rst
  doc/variableexplorer.rst
Labels: type:Task

#149 PR: Decrease length of headers in installation guide
  doc/installation.rst
Labels: type:Task

#145 PR: Update footer config
  doc/conf.py
Labels: type:Task

#153 PR: Fix typo in CSS resulting in blue icons not working
  doc/_static/custom_styles.css
Labels: type:Bug

#154 PR: Make navbar have a similar look to the one on the main website
  doc/_static/custom_styles.css
  doc/conf.py
Labels: type:Task

#157 PR: Add icons to Additional Help section of installation guide
  doc/installation.rst
Labels: status:Ready for Review, type:Enhancement

#151 PR: Cleanup a few accumulated formatting issues on rewritten docs
  doc/_static/custom_styles.css
  doc/findinfiles.rst
  doc/first-steps-with-spyder.rst
  doc/indexpanes.rst
  doc/indexvideos.rst
  doc/plots.rst
  doc/profiler.rst
  doc/variableexplorer.rst
  doc/working-with-spyder.rst
Labels: status:Ready for Review, type:Task

#161 PR: Update the readme for Spyder 4 and convert it to sentence breaks from hard breaks
  README.md
Labels: status:Ready for Review, type:Spyder Change

#166 PR: Fix Font Awesome icons to be centered on their lines
  doc/_static/custom_styles.css
  doc/index.rst
Labels: status:Ready for Review, type:Bug

#168 PR: Add support to build pull request previews with Netlify
  .travis.yml
  CONTRIBUTING.md
  ci/install.sh
  runtime.txt
Labels: status:Ready for Review, type:Task

#169 PR: Include overview item in sidebar pointing to index
  doc/index.rst
Labels: type:Task

#175 PR: Add videos on profiling and code analysis to "Working with Spyder" section
  doc/working-with-spyder.rst
Labels: type:New Doc

#160 PR: Remove Spyder badges from Readme
  README.md
Labels: type:Task

#158 PR: Update style and contributing guide to reflect Spyder 4 release, recent changes to the repo and be more usable for new contributors
  CONTRIBUTING.md
  STYLEGUIDE.md
Labels: status:Ready for Review, type:Enhancement

#167 PR: Add troubleshooting section to docs
  doc/_static/custom_styles.css
  doc/basic-first-aid.rst
  doc/call-for-help.rst
  doc/common-illnesses.rst
  doc/emergency-cpr.rst
  doc/first-steps.rst
  doc/images/basic-first-aid/basic-first-aid-app-data.gif
  doc/images/basic-first-aid/basic-first-aid-internal-console.png
  doc/images/basic-first-aid/basic-first-aid-qtconsole.png
  doc/images/basic-first-aid/basic-first-aid-updates.png
  doc/images/common-illnesses/common-illnesses-LSP-restart.png
  doc/images/common-illnesses/common-illnesses-atribute-error.png
  doc/images/common-illnesses/common-illnesses-kernel-version.png
  doc/images/common-illnesses/common-illnesses-missing-docstring.png
  doc/images/common-illnesses/common-illnesses-not-found.png
  doc/images/common-illnesses/common-illnesses-plugins.png
  doc/images/emergency-cpr/emergency-cpr-python-start.gif
  doc/images/emergency-cpr/emergency-cpr-single-instance.png
  doc/images/first-steps/first-steps-show-details.png
  doc/images/submit-a-report/submit-a-report-conda-list.png
  doc/images/submit-a-report/submit-a-report-error-dialog.png
  doc/images/submit-a-report/submit-a-report-issue-template.png
  doc/images/submit-a-report/submit-a-report-issue-tracker.png
  doc/images/submit-a-report/submit-a-report-issue.png
  doc/images/submit-a-report/submit-a-report-spyder-info.png
  doc/index.rst
  doc/indextroubleshooting.rst
  doc/submit-a-report.rst
Labels: status:Ready for Review, type:New Doc

#177 PR: Change screenshots for ones with dark-mode, fix pane names
  doc/debugging.rst
  doc/editor.rst
  doc/fileexplorer.rst
  doc/historylog.rst
  doc/images/console/console-completion.png
  doc/images/console/console-dialog-connect.png
  doc/images/console/console-menu.png
  doc/images/console/console-standard.png
  doc/images/console/console_completion.png
  doc/images/console/console_dialog_connect.png
  doc/images/console/console_menu.png
  doc/images/console/console_standard.png
  doc/images/debugging/breakpoints-standard.png
  doc/images/debugging/breakpoints_standard.png
  doc/images/debugging/debugging-condbreakpoint.png
  doc/images/debugging/debugging-console.png
  doc/images/debugging/debugging_condbreakpoint.png
  doc/images/debugging/debugging_console.png
  doc/images/dialog/dialog_new_project.png
  doc/images/editor/editor-cells.png
  doc/images/editor/editor-inset-code-analysis.png
  doc/images/editor/editor-outline-standard.png
  doc/images/editor/editor-standard.png
  doc/images/editor/editor_inset_code_analysis.png
  doc/images/editor/editor_split_horizontal.png
  doc/images/editor/editor_split_vertical.png
  doc/images/editor/editor_standard.png
  doc/images/editor/outline_standard.png
  doc/images/file_explorer/file_explorer_contextmenu_new.png
  doc/images/file_explorer/file_explorer_standard.png
  doc/images/files/files-contextmenu-new.png
  doc/images/files/files-standard.png
  doc/images/history/history-menu.png
  doc/images/history_log/history_log_menu.png
  doc/images/other/git-for-windows-install-path.png
  doc/images/projects/project_explorer_inset_contextmenu.png
  doc/images/projects/project_explorer_standard.png
  doc/images/projects/projects-new-project.png
  doc/images/projects/projects-standard.png
  doc/indexpanes.rst
  doc/ipythonconsole.rst
  doc/projects.rst
Labels: type:Spyder Change

#174 PR: Add FAQ section to docs
  doc/_static/custom_styles.css
  doc/common-illnesses.rst
  doc/conf.py
  doc/faq.rst
  doc/images/faq/faq-cells.png
  doc/images/faq/faq-change-language.png
  doc/images/faq/faq-conda-info.png
  doc/images/faq/faq-highlighting-theme.png
  doc/images/faq/faq-launch-anaconda.png
  doc/images/faq/faq-navigator-install.png
  doc/images/faq/faq-python-interpreter.png
  doc/images/faq/faq-remove-variables.png
  doc/images/faq/faq-reset-spyder.png
  doc/images/faq/faq-run-environment.png
  doc/images/faq/faq-run-options.png
  doc/images/faq/faq-windows-launch.png
  doc/index.rst
Labels: type:New Doc

#178 PR: Update the docs repo to work with the new theme changes
  STYLEGUIDE.md
  doc/basic-first-aid.rst
  doc/conf.py
  doc/debugging.rst
  doc/editor.rst
  doc/fileexplorer.rst
  doc/findinfiles.rst
  doc/help.rst
  doc/historylog.rst
  doc/installation.rst
  doc/internalconsole.rst
  doc/onlinehelp.rst
  doc/plots.rst
  doc/profiler.rst
  doc/projects.rst
  doc/pylint.rst
  doc/variableexplorer.rst
Labels: type:Task

#176 PR: Fix margins for iframes
  doc/_static/custom_styles.css
  doc/conf.py
Labels: type:Task

#171 PR: Add Quickstart page containing an interactive tour of Spyder's UI
  doc/_static/custom_scripts.js
  doc/_static/custom_styles.css
  doc/_static/driver.min.css
  doc/_static/driver.min.js
  doc/_static/tour/code-analysis.png
  doc/_static/tour/context-menu.png
  doc/_static/tour/default-layout-main.png
  doc/_static/tour/files.png
  doc/_static/tour/find.png
  doc/_static/tour/options-menu.png
  doc/_static/tour/plots.png
  doc/_static/tour/profiler.png
  doc/_static/tour/variable-explorer.png
  doc/conf.py
  doc/index.rst
  doc/overview.rst
  doc/quickstart.rst
Labels: type:New Doc

#186 PR: Add build.sh script to run from Netlify
  ci/build.sh
Labels: type:Task

#190 PR: Implement docs repo-side final style changes for release
  doc/_static/spyder_logo.png
  doc/_static/spyder_logo_docs.png
  doc/conf.py
Labels: type:Enhancement

#191 PR: Set doctr deploy directory to root per multiversion changes
  .travis.yml
Labels: type:Bug

#192 PR: Check CI variables to properly detect branch when HEAD detached
  .travis.yml
  ci/install.sh
  scripts/tagcurrent.py
Labels: type:Task

#193 PR: Fix title of redirect to look better on previews
  scripts/generateredirects.py
Labels: type:Task

#194 PR: Change screenshot in README to GIF of the new Spyder 4 docs
  README.md
  doc/_static/index-docs.gif
  doc/_static/index_screenshot.png
Labels: type:Spyder Change
