Repository spyder-ide/spyder-docs, pull requests merged in 2020-06, with the labels that each got.

#115 PR: Regenerate deploy key and .travis.yml to get CI build working again
  .travis.yml
  doc/installation.rst
  doc/pylint.rst
  github_deploy_key_spyder_ide_spyder_docs.enc
Labels: type:Task

#112 PR: Update Code Analysis pane documentation for Spyder 4
  doc/images/pylint/code-analysis-editor.gif
  doc/images/pylint/code-analysis-expand-collapse.gif
  doc/images/pylint/code-analysis-file.gif
  doc/images/pylint/code-analysis-history-custom.gif
  doc/images/pylint/code-analysis-history.png
  doc/images/pylint/code-analysis-output.png
  doc/images/pylint/code-analysis-pylint-disable.gif
  doc/images/pylint/code-analysis-pylint-file.gif
  doc/images/pylint/code-analysis-standard.png
  doc/images/pylint/static_analysis_standard.png
  doc/pylint.rst
Labels: type:Spyder Change

#106 PR: Add current version of docs style guide
  STYLEGUIDE.md
Labels: status:Ready for Review, type:Task

#120 PR: Update index to show only the panes that are ready
  doc/debugging.rst
  doc/editor.rst
  doc/fileexplorer.rst
  doc/findinfiles.rst
  doc/historylog.rst
  doc/index.rst
  doc/installation.rst
  doc/internalconsole.rst
  doc/ipythonconsole.rst
  doc/onlinehelp.rst
  doc/options.rst
  doc/overview.rst
  doc/profiler.rst
  doc/projects.rst
Labels: type:Task

#124 PR Add rst for videos section 1 and 2, add directive for videos in conf
  doc/conf.py
  doc/first-steps-with-spyder.rst
  doc/index.rst
  doc/indexvideos.rst
  doc/working-with-spyder.rst
Labels: type:New Doc

#126 PR: Update index for docs and add panes index
  doc/index.rst
  doc/indexpanes.rst
Labels: type:Enhancement

#121 PR: Add profiler docs to index and improve language
  doc/images/profiler/profiler-comparison.png
  doc/images/profiler/profiler-dropdown.gif
  doc/images/profiler/profiler-execution-browse.gif
  doc/images/profiler/profiler-execution-menu.gif
  doc/images/profiler/profiler-line-profiler.png
  doc/images/profiler/profiler-memory-profiler.png
  doc/images/profiler/profiler-open-file.gif
  doc/images/profiler/profiler-previous-paths.png
  doc/images/profiler/profiler-save-load.gif
  doc/images/profiler/profiler-standard.png
  doc/images/profiler/profiler_comparison.png
  doc/images/profiler/profiler_standard.png
  doc/index.rst
  doc/indexpanes.rst
  doc/profiler.rst
Labels: status:Ready for Review, type:Spyder Change
