Repository spyder-ide/spyder-docs, pull requests merged in 2020-12, with the labels that each got.

#207 PR: Add anchors, direct links and buttons to dropdowns, and open and scroll to them automatically
  doc/_static/custom_scripts.js
  doc/_static/custom_styles.css
  doc/faq.rst
Labels: type:Enhancement

#206 PR: Add FAQ question on installing Spyder on macOS Big Sur
  doc/faq.rst
Labels: type:Spyder Change

#209 PR: Update the navbar to be consistant with the rest of the website
  doc/conf.py
Labels: type:Task

#146 PR: Update and improve the content of the Files pane docs
  doc/fileexplorer.rst
  doc/images/files/files-associations-open.gif
  doc/images/files/files-associations.gif
  doc/images/files/files-browse.gif
  doc/images/files/files-columns-display.png
  doc/images/files/files-commit.gif
  doc/images/files/files-context-menu.png
  doc/images/files/files-contextmenu-new.png
  doc/images/files/files-copy-path.gif
  doc/images/files/files-filters.gif
  doc/images/files/files-standard.png
Labels: type:Enhancement, type:Spyder Change

#210 PR: Add new kernel versions in troubleshooting and FAQ
  doc/common-illnesses.rst
  doc/faq.rst
Labels: type:Spyder Change

#205 PR: Add FAQ questions on Spyder being open source and Anaconda situation
  doc/faq.rst
Labels: type:Enhancement

#208 PR: Add more content to the debugger and breakpoint docs and update them for Spyder 4
  doc/debugging.rst
  doc/images/debugging/breakpoints-standard.png
  doc/images/debugging/debugging-arrow.png
  doc/images/debugging/debugging-autocompletion.gif
  doc/images/debugging/debugging-breakpoints.gif
  doc/images/debugging/debugging-commands.gif
  doc/images/debugging/debugging-commands.png
  doc/images/debugging/debugging-condbreakpoint.png
  doc/images/debugging/debugging-console.png
  doc/images/debugging/debugging-libraries.png
  doc/images/debugging/debugging-matplotlib.gif
  doc/images/debugging/debugging-multiline.gif
  doc/images/debugging/debugging-snippet.png
  doc/images/debugging/debugging-timeit.png
  doc/images/debugging/debugging-variables.png
  doc/indexpanes.rst
Labels: type:Enhancement, type:Spyder Change

#211 PR: Improve content and organization of history pane in docs
  doc/historylog.rst
  doc/images/history/history-log-file.png
  doc/images/history/history-menu.png
  doc/images/history/history-standard.png
  doc/images/history/history-wrap.gif
Labels: type:Enhancement

#214 PR: Improve phrasing for the projects docs
  doc/fileexplorer.rst
  doc/images/projects/projects-main.png
  doc/images/projects/projects-new-project.png
  doc/images/projects/projects-new.gif
  doc/images/projects/projects-standard.png
  doc/projects.rst
Labels: type:Enhancement
