Repository spyder-ide/spyder-docs, pull requests merged in 2020-07, with the labels that each got.

#125 PR: Fix Online help docs
  doc/images/online_help/online-help-browse.gif
  doc/images/online_help/online-help-find.gif
  doc/images/online_help/online-help-history.png
  doc/images/online_help/online-help-name.gif
  doc/images/online_help/online-help-navigation.gif
  doc/images/online_help/online-help-path.gif
  doc/images/online_help/online-help-python-docs.gif
  doc/images/online_help/online-help-refresh.gif
  doc/images/online_help/online-help-search.gif
  doc/images/online_help/online-help-standard.png
  doc/images/online_help/online-help-topics.png
  doc/images/online_help/online-help-zoom.gif
  doc/images/online_help/online_help_standard.png
  doc/indexpanes.rst
  doc/onlinehelp.rst
Labels: type:Spyder Change

#128 PR: Update install guide for Spyder 4, remove outdated sections, fix outstanding issues and add Binder
  doc/index.rst
  doc/installation.rst
Labels: type:Spyder Change

#130 PR: Add gifs and images to installation guide in docs
  doc/images/installation/installation-anaconda-navigator.png
  doc/images/installation/installation-conda-install.gif
  doc/images/installation/installation-pip-install.gif
  doc/images/installation/installation-spyder-binder.png
  doc/installation.rst
Labels: type:Enhancement

#129 PR: Overhaul index page with new and updated content for Spyder 4
  doc/_static/Ipython.png
  doc/_static/book-open-solid.png
  doc/_static/book-solid.png
  doc/_static/columns-solid.png
  doc/_static/cython-logo-C.svg
  doc/_static/download-solid.png
  doc/_static/first-aid-solid.png
  doc/_static/globe-americas-solid.png
  doc/_static/ipython_trans.png
  doc/_static/laptop-code-solid.png
  doc/_static/matplotlib_logo.svg
  doc/_static/numpylogo.svg
  doc/_static/pandas.png
  doc/_static/question-circle-solid.png
  doc/_static/scipy.png
  doc/_static/scipy_trans.png
  doc/_static/sympy.png
  doc/_static/sympy_logo_trans.png
  doc/_static/user-friends-solid.png
  doc/_static/walking-solid.png
  doc/images/mainwindow/mainwindow_default_1610.png
  doc/index.rst
Labels: status:Ready for Review, type:Enhancement, type:Spyder Change

#127 PR: Use new theme
  .gitignore
  .travis.yml
  CONTRIBUTING.md
  Makefile
  doc/_static/custom.css
  doc/_static/spyder_logo.png
  doc/_templates/layout.html
  doc/conf.py
Labels: type:Enhancement

#134 PR: Add Font Awesome icon support and replace icons in index with them; fix makefile
  .travis.yml
  Makefile
  doc/_static/book-open-solid.png
  doc/_static/book-solid.png
  doc/_static/columns-solid.png
  doc/_static/custom_styles.css
  doc/_static/download-solid.png
  doc/_static/first-aid-solid.png
  doc/_static/globe-americas-solid.png
  doc/_static/laptop-code-solid.png
  doc/_static/question-circle-solid.png
  doc/_static/user-friends-solid.png
  doc/_static/walking-solid.png
  doc/conf.py
  doc/index.rst
Labels: status:Ready for Review, type:Enhancement

#135 PR: Fix spaces in docs files to fit new theme
  doc/first-steps-with-spyder.rst
  doc/help.rst
  doc/index.rst
  doc/installation.rst
  doc/onlinehelp.rst
  doc/plots.rst
  doc/profiler.rst
  doc/pylint.rst
  doc/variableexplorer.rst
  doc/working-with-spyder.rst
Labels: type:Enhancement

#141 PR: Add cards directive
  .travis.yml
  CONTRIBUTING.md
  doc/_static/custom_styles.css
  doc/conf.py
  doc/index.rst
Labels: type:Enhancement
