Repository spyder-ide/spyder-docs, pull requests merged in 2021-09, with the labels that each got.

#274 PR: Add documentation for Line Profiler plugin
  doc/images/lineprofiler/lineprofiler-add-decorators.gif
  doc/images/lineprofiler/lineprofiler-overview.png
  doc/images/lineprofiler/lineprofiler-run-menu.png
  doc/images/lineprofiler/lineprofiler-run-profiler.gif
  doc/images/lineprofiler/lineprofiler-view-panes.png
  doc/plugins/lineprofiler.rst
Labels: type:New Doc

#282 PR: Fix standalone installers and packages dropdown in FAQ showing id as text
  doc/_static/css/custom_styles.css
  doc/faq.rst
Labels: type:Bug

#286 PR: Fix pre-commit and linkcheck failures on master due to workshops
  .pre-commit-config.yaml
  doc/conf.py
  doc/workshops/financial-analysis.py
  doc/workshops/financial.rst
  doc/workshops/scientific-computing.py
  doc/workshops/scientific-computing.rst
Labels: type:Techdebt

#287 PR: Move tour images out of _static to ensure they are unique per-version
  doc/_assets/assets/tour/code-analysis.png
  doc/_assets/assets/tour/context-menu.png
  doc/_assets/assets/tour/default-layout-main.png
  doc/_assets/assets/tour/files.png
  doc/_assets/assets/tour/find.png
  doc/_assets/assets/tour/options-menu.png
  doc/_assets/assets/tour/plots.png
  doc/_assets/assets/tour/profiler.png
  doc/_assets/assets/tour/variable-explorer.png
  doc/conf.py
  doc/quickstart.rst
Labels: type:Bug

#288 PR: Fix tour images shared between versions properly w/unique paths
  doc/_assets/assets/4/tour/tour-code-analysis.png
  doc/_assets/assets/4/tour/tour-context-menu.png
  doc/_assets/assets/4/tour/tour-default-layout-main.png
  doc/_assets/assets/4/tour/tour-files.png
  doc/_assets/assets/4/tour/tour-find.png
  doc/_assets/assets/4/tour/tour-options-menu.png
  doc/_assets/assets/4/tour/tour-plots.png
  doc/_assets/assets/4/tour/tour-profiler.png
  doc/_assets/assets/4/tour/tour-variable-explorer.png
  doc/quickstart.rst
Labels: type:Bug

#294 PR: Optimize loading-critical tour images for Spyder 4
  doc/_assets/assets/4/tour/tour-code-analysis.png
  doc/_assets/assets/4/tour/tour-context-menu.png
  doc/_assets/assets/4/tour/tour-default-layout-main.png
  doc/_assets/assets/4/tour/tour-files.png
  doc/_assets/assets/4/tour/tour-find.png
  doc/_assets/assets/4/tour/tour-options-menu.png
  doc/_assets/assets/4/tour/tour-plots.png
  doc/_assets/assets/4/tour/tour-profiler.png
  doc/_assets/assets/4/tour/tour-variable-explorer.png
Labels: type:Task

#295 PR: Optimize frequently-loaded & loading critical tour images for Spyder 5
  doc/_assets/assets/5/tour/tour-code-analysis.png
  doc/_assets/assets/5/tour/tour-context-menu.png
  doc/_assets/assets/5/tour/tour-default-layout-main.png
  doc/_assets/assets/5/tour/tour-files.png
  doc/_assets/assets/5/tour/tour-find.png
  doc/_assets/assets/5/tour/tour-options-menu.png
  doc/_assets/assets/5/tour/tour-plots.png
  doc/_assets/assets/5/tour/tour-profiler.png
  doc/_assets/assets/5/tour/tour-variable-explorer.png
  doc/_static/images/spyder_logo.png
  doc/_static/images/spyder_readme_banner.png
Labels: type:Task
