Repository spyder-ide/spyder-docs, pull requests merged in 2021-04, with the labels that each got.

#213 PR: Add more content to IPython console docs and make text more friendly
  doc/images/console/console-connect-local-step1.gif
  doc/images/console/console-connect-local-step2.gif
  doc/images/console/console-connect-local-step3.gif
  doc/images/console/console-connect-remote-step1.gif
  doc/images/console/console-connect-remote-step2.gif
  doc/images/console/console-connect-remote-step3.gif
  doc/images/console/console-connect-remote-step4.gif
  doc/images/console/console-connect-remote-step5.gif
  doc/images/console/console-new.gif
  doc/images/console/console-options-menu.png
  doc/images/console/console-reload-modules.png
  doc/images/console/console-rename.gif
  doc/images/console/console-special.gif
  doc/images/console/console-umr-preferences.png
  doc/ipythonconsole.rst
Labels: type:Enhancement, type:Spyder Change

#223 PR: Bump version on master to Spyder 5 and rebuild
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
  README.md
  doc/conf.py
  doc/faq.rst
  doc/installation.rst
Labels: type:Spyder Change, type:Task

#224 PR: Change Spyder image in welcome page to Spyder 5 version
  doc/images/mainwindow/mainwindow_default_1610.png
Labels: type:Spyder Change
