Repository spyder-ide/spyder-docs, pull requests merged in 2021-10, with the labels that each got.

#293 PR: Add explanation on the use of subsections in the Outline Explorer
  doc/images/editor/editor-subsections.png
  doc/panes/editor.rst
Labels: type:Enhancement

#289 PR: Improve tour on mobile by moving popover and thickening outline
  doc/_static/css/custom_styles.css
  doc/_static/js/custom_scripts.js
Labels: type:Bug

#291 PR: Clarify line limit and how to clear history log
  doc/panes/historylog.rst
Labels: type:Enhancement

#290 PR: Add banner for out of date and development versions
  doc/_templates/layout.html
  doc/conf.py
Labels: type:Task

#298 PR: Add FAQ question about installing Spyder on WSL2
  doc/faq.rst
Labels: type:Enhancement

#299 PR: Move sub-indicies to subdirectories where they belong
  doc/index.rst
  doc/indextroubleshooting.rst
  doc/indexvideos.rst
  doc/panes/index.rst
  doc/plugins/index.rst
  doc/troubleshooting/index.rst
  doc/videos/index.rst
Labels: type:Techdebt

#283 PR: Don't show plugins in index that aren't yet compatible with Spyder 5
  doc/plugins/index.rst
  doc/plugins/lineprofiler.rst
  doc/plugins/notebook.rst
Labels: type:Spyder Change

#292 PR: Uncollapse dropdowns that contain highlighted words (e.g. from search)
  doc/_static/js/custom_scripts.js
Labels: type:Enhancement
