Repository spyder-ide/spyder-docs, pull requests merged in 2021-12, with the labels that each got.

#302 PR: Pin Python version on CIs to 3.9 to fix build failures with 3.10
  .github/workflows/build.yaml
  .github/workflows/check.yaml
  .github/workflows/deploy.yaml
  .github/workflows/lint.yaml
Labels: type:Techdebt

#303 PR: Fix broken links to SciPy site and others in workshops
  doc/workshops/financial.rst
  doc/workshops/plugin-development.rst
  doc/workshops/scientific-computing.rst
Labels: type:Bug

#301 PR: Adapt plugin workshop to the most recent version of cookiecutter
  doc/workshops/plugin-development.rst
Labels: type:Spyder Change
