Repository spyder-ide/spyder-docs, pull requests merged in 2022-11, with the labels that each got.

#335 Revise Install Guide to provide better, more up to date guidance
  doc/faq.rst
  doc/installation.rst
  doc/plugins/lineprofiler.rst
  doc/plugins/notebook.rst
  doc/plugins/terminal.rst
  doc/workshops/financial.rst
  doc/workshops/plugin-development.rst
  doc/workshops/scientific-computing.rst
Labels: type:Enhancement, type:Spyder Change

#331 Overhaul Editor doc with many new sections and screenshots
  doc/images/editor/editor-autoformat-setting.png
  doc/images/editor/editor-automatic-formatting.gif
  doc/images/editor/editor-class-function-selector.gif
  doc/images/editor/editor-code-completion.png
  doc/images/editor/editor-code-style-setting.png
  doc/images/editor/editor-file-switcher.gif
  doc/images/editor/editor-file-switcher.png
  doc/images/editor/editor-find-replace-panel.png
  doc/images/editor/editor-go-to-definition.gif
  doc/images/editor/editor-go-to-line.gif
  doc/images/editor/editor-hoverhint.png
  doc/images/editor/editor-linting-setting.png
  doc/images/editor/editor-pane-code-error.png
  doc/images/editor/editor-run-configuration.png
  doc/images/editor/editor-split-panels.gif
  doc/images/editor/editor-syntax-highlighting.gif
  doc/images/editor/editor-tabs-browser.png
  doc/images/editor/editor-tabs-sorting.gif
  doc/panes/editor.rst
  doc/panes/help.rst
Labels: type:Enhancement

#338 Add latest Spyder version in Anaconda to update command
  doc/installation.rst
Labels: type:Bug
