Repository spyder-ide/spyder-docs, pull requests merged in 2024-02, with the labels that each got.

#359 Add/update links to separate M1 and Intel macOS installers
  doc/_static/css/custom_styles.css
  doc/installation.rst
Labels: type:Spyder Change, 5.x

#360 Run linkcheck weekly and silences SO/SE failures due to blocking GHA
  .github/workflows/check.yaml
  doc/conf.py
Labels: type:Task

#358 Refine commands & Add/update links in contributing guide
  CONTRIBUTING.md
Labels: type:Task

#361 Update troubleshooting link in install guide to internal one
  doc/installation.rst
  doc/troubleshooting/first-steps.rst
Labels: type:Bug
