Repository spyder-ide/spyder-docs, pull requests merged in 2024-09, with the labels that each got.

#378 Fix download links now broken in Spyder 6 & fix error w/stylelint
  .pre-commit-config.yaml
  doc/_static/css/custom_styles.css
  doc/installation.rst
  doc/videos/first-steps-with-spyder.rst
Labels: type:Task, type:Spyder Change, 6.x

#377 Migrate docs infrastructure from Make to Nox
  .github/workflows/build.yaml
  .github/workflows/check.yaml
  CONTRIBUTING.md
  Makefile
  README.md
  ci/build.sh
  ci/install.sh
  doc/Makefile
  doc/make.bat
  noxfile.py
  scripts/safecopy.py
Labels: type:Techdebt

#379 Improve and refactor noxfile to prepare for translation commands
  CONTRIBUTING.md
  noxfile.py
  requirements.txt
Labels: type:Task

#380 Add docs translation and the infrastructure and automation it requires
  .github/workflows/build.yaml
  .pre-commit-config.yaml
  ci/build.sh
  crowdin.yml
  doc/conf.py
  doc/locales/en/LC_MESSAGES/faq.po
  doc/locales/en/LC_MESSAGES/index.po
  doc/locales/en/LC_MESSAGES/installation.po
  doc/locales/en/LC_MESSAGES/panes.po
  doc/locales/en/LC_MESSAGES/plugins.po
  doc/locales/en/LC_MESSAGES/quickstart.po
  doc/locales/en/LC_MESSAGES/troubleshooting.po
  doc/locales/en/LC_MESSAGES/videos.po
  doc/locales/en/LC_MESSAGES/workshops.po
  doc/locales/es/LC_MESSAGES/faq.po
  doc/locales/es/LC_MESSAGES/index.po
  doc/locales/es/LC_MESSAGES/installation.po
  doc/locales/es/LC_MESSAGES/panes.po
  doc/locales/es/LC_MESSAGES/plugins.po
  doc/locales/es/LC_MESSAGES/quickstart.po
  doc/locales/es/LC_MESSAGES/troubleshooting.po
  doc/locales/es/LC_MESSAGES/videos.po
  doc/locales/es/LC_MESSAGES/workshops.po
  doc/locales/pot/faq.pot
  doc/locales/pot/index.pot
  doc/locales/pot/installation.pot
  doc/locales/pot/panes.pot
  doc/locales/pot/plugins.pot
  doc/locales/pot/quickstart.pot
  doc/locales/pot/troubleshooting.pot
  doc/locales/pot/videos.pot
  doc/locales/pot/workshops.pot
  noxfile.py
Labels: type:Enhancement

#381 Regenerate translation files with current infra and update with new strings
  doc/conf.py
  doc/locales/en/LC_MESSAGES/faq.po
  doc/locales/en/LC_MESSAGES/index.po
  doc/locales/en/LC_MESSAGES/installation.po
  doc/locales/en/LC_MESSAGES/panes.po
  doc/locales/en/LC_MESSAGES/plugins.po
  doc/locales/en/LC_MESSAGES/quickstart.po
  doc/locales/en/LC_MESSAGES/troubleshooting.po
  doc/locales/en/LC_MESSAGES/videos.po
  doc/locales/en/LC_MESSAGES/workshops.po
  doc/locales/pot/faq.pot
  doc/locales/pot/index.pot
  doc/locales/pot/installation.pot
  doc/locales/pot/panes.pot
  doc/locales/pot/plugins.pot
  doc/locales/pot/quickstart.pot
  doc/locales/pot/troubleshooting.pot
  doc/locales/pot/videos.pot
  doc/locales/pot/workshops.pot
  noxfile.py
Labels: type:Techdebt

#382 Fix Sphinx Lint for Spanish translations
  doc/locales/es/LC_MESSAGES/panes.po
  doc/locales/es/LC_MESSAGES/troubleshooting.po
Labels: type:Bug

#383 Update pre-commit hooks and config for 2024-09
  .eslintrc.json
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/lint.yaml
  .gitignore
  .markdownlint.json
  .markdownlint.yaml
  .pre-commit-config.yaml
  .prettierrc.yaml
  .stylelintrc.json
  .yamllint.yml
  CONTRIBUTING.md
  README.md
  SECURITY.md
  STYLEGUIDE.md
  doc/_static/js/custom_scripts.js
  eslint.config.js
Labels: type:Task, type:Techdebt

#384 Add Nox setup & setup-remotes commands + other improvements
  CONTRIBUTING.md
  noxfile.py
Labels: type:Enhancement
